# Это рабочий вариант. Роутинг определяется аннотациями Symfony
iff_chat:
    resource: "@IFFChatBundle/Controller/"
    type: annotation
    
    
# Этот вариант гипотетичесикй подробный )))
#iff_chat_homepage:
#    path:     /
#    defaults: { _controller: IFFChatBundle:Chat:index }
#    
#iff_chat_saving:
#    path:     /saving
#    defaults: { _controller: IFFChatBundle:Chat:saveMessages }
#    
#iff_chat_loading:
#    path:     /loading
#    defaults: { _controller: IFFChatBundle:Chat:loadMessages }
